# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd97a81958b190d627325798cc948d60cef8fe697f49d6e4b319c1aba3373ad22d859f606b092d4d4aa8d82faf82ca0aff7d5b6e9ba163a55dd83e6eb73d497a

test:
  secret_key_base: f080b1e2b71ead919ef75b5d71d63023d47652b26cb60d8c77e9c43e66ac3f858663171c6120ee243f62da7166805b65345caa5b545631e2528bce5c5f884688

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
